In [12]:

#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Reading Training CSV file"""

#Train.csv file is read
data=pd.read_csv("train.csv")
data.head()

               Sequence   Label
0    AAAFVNQHLCGSHLVEAL       0
1    AACFKEGSFDEDGFYAKV       0
2   AAEELMNALVNSTLLETRT       0
3  AAGTAAGGKNFVIQKSEKSE       0
4  AAHCVANVNVRAVRVVLGAH       0

In [13]:
#Test data is read
test_data=pd.read_csv("test.csv")
test_data.head()

      ID               Sequence
0  10001      AAAEQLKTTRNAYHQKY
1  10002       AAALAPTQTRAGPHSL
2  10003           AADLALATVNEL
3  10004  AAHPDKRGEDQAEGLPEEVRG
4  10005   AAKPKRAKASKKSTDHPKYS

In [14]:
train_f=pd.read_csv('train_feature.csv')
test_f=pd.read_csv('test_feature.csv')
X_train=train_f#train dataset
y_train=data[' Label']# Label class from train dataset
X_test=test_f#test dataset

In [15]:
X_train

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,TPC_YYM,TPC_YYN,TPC_YYP,TPC_YYQ,TPC_YYR,TPC_YYS,TPC_YYT,TPC_YYV,TPC_YYW,TPC_YYY
0,22.22,5.56,0.00,5.56,5.56,5.56,11.11,0.00,0.00,16.67,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,16.67,5.56,11.11,11.11,16.67,11.11,0.00,0.00,11.11,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,15.79,0.00,0.00,15.79,0.00,0.00,0.00,0.00,0.00,21.05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20.00,0.00,0.00,10.00,5.00,15.00,0.00,5.00,15.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,25.00,5.00,0.00,0.00,0.00,5.00,10.00,0.00,0.00,5.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8388,26.67,0.00,0.00,0.00,0.00,6.67,0.00,13.33,6.67,13.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8389,5.00,0.00,5.00,20.00,0.00,5.00,0.00,15.00,20.00,10.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8390,6.67,0.00,0.00,6.67,6.67,26.67,0.00,6.67,13.33,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8391,7.69,0.00,0.00,15.38,0.00,0.00,0.00,7.69,7.69,7.69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8392,13.33,0.00,13.33,6.67,6.67,0.00,0.00,13.33,6.67,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
#importing libraries needed
import itertools
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
import lightgbm as lgb
# Classifiers
from sklearn.svm import NuSVC, SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [17]:
# Initializing Support Vector  classifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, StackingClassifier,ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier

classifier1 = SVC()

# Initializing Multi-layer perceptron  classifier
classifier2 = MLPClassifier()

# Initialing Decision Tree classifier
classifier3 = DecisionTreeClassifier(max_depth=5)

# Initializing Random Forest classifier
classifier4 = RandomForestClassifier()

# Initializing Navies Bayes classifier
classifier5=GaussianNB()

# Initializing K Nearest Neighbour  classifier
classifier6 = KNeighborsClassifier(3)



# Stacked generalization consists in stacking the output of individual estimator and 
# use a classifier to compute the final prediction. Stacking allows to use the strength 
# of each individual estimator by using their output as input of a final estimator.
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [18]:
# Define estimators
from sklearn.ensemble import ExtraTreesClassifier
estimator_list = [
    ('classifier1',classifier1),
    ('classifier2',classifier2),
    ('classifier3',classifier3),
    ('classifier4',classifier4),
    ('classifier5',classifier5),
    ('classifier6',classifier6),
    ]

# Build stack model
stack_model = StackingClassifier(
    estimators=estimator_list, final_estimator=LogisticRegression()
)
stack_model.fit(X_train,y_train)

In [9]:
y_test_pred_prob = stack_model.predict_proba(X_test)

In [10]:
# Select class 1 probability
y_test_pred = y_test_pred_prob[:, 1]

In [11]:
df2 = pd.DataFrame(y_test_pred, columns=['Label'])
test_data=pd.read_csv("test.csv")
id=test_data['ID']
result3 = pd.concat([id, df2], axis=1, join="inner")

result3.to_csv('group10_output.csv', index=False)